// Marketing Overview — the single top-of-funnel screen.
//
// Lead Sources used to be its own tab; it is folded in here because "which
// channels bring leads" is the same question this page already answers with the
// donut, just at table depth. The page also carries two compact activity strips:
// Click-to-WhatsApp (are the ads producing conversations?) and Conversion API
// (is Meta being told what those conversations became?), each linking to its own
// tab for the detail.
import { useState, useEffect, useCallback } from 'react';
import {
  Users, IndianRupee, Megaphone, GraduationCap, GitBranch, MousePointerClick,
  ArrowRight, AlertTriangle, CheckCircle2,
} from 'lucide-react';
import { api } from '../../api.js';
import { C, FONT, MONO } from '../../constants.js';
import { showError } from '../../lib/feedback.js';
import { PageShell, Segmented, Table, Td, EmptyState, Badge, fmtINR, fmtDate, STAGE_META } from '../academy/shared.jsx';
import { KpiCard, Card, Donut, FunnelBars, LineTrend, Shimmer, SERIES } from '../../components/charts.jsx';
import SearchableSelect from '../../components/SearchableSelect.jsx';
import { useFunnelConfig } from '../../hooks/useFunnelConfig.js';

const RANGES = [{ value: 30, label: '30 days' }, { value: 90, label: '90 days' }];

function num(n) { return Number(n || 0).toLocaleString('en-IN'); }

export default function OverviewPage({ user, navigate }) {
  const { sources: sourceOptions } = useFunnelConfig();
  const [days, setDays] = useState(30);
  const [source, setSource] = useState('');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  // Folded-in Lead Sources table.
  const [sources, setSources] = useState(null);

  // Activity strips. Both are best-effort: this page must still render for a
  // user whose role can't reach those tabs, so a rejection means "hide the
  // strip", never an error modal.
  const [ctwa, setCtwa] = useState(null);

  const isAdmin = user?.role === 'admin';
  const canSeeCtwa = isAdmin || (user?.pages || []).includes('ctwa-ads');

  const load = useCallback(async () => {
    setLoading(true);
    try { setData(await api.marketing.overview(days, source || undefined)); }
    catch (e) { showError(e.message); }
    finally { setLoading(false); }
  }, [days, source]);
  useEffect(() => { load(); }, [load]);

  useEffect(() => {
    api.leads.sources().then(d => setSources(d.sources)).catch(() => setSources([]));
  }, []);

  useEffect(() => {
    if (!canSeeCtwa) { setCtwa(false); return; }
    api.ctwa.overview({ days: String(days) }).then(setCtwa).catch(() => setCtwa(false));
  }, [days, canSeeCtwa]);

  const k = data?.kpis || {};

  return (
    <PageShell
      title="Marketing Overview"
      subtitle="Single-glance top-of-funnel health check — where leads come from, and what the ad loop is doing."
      actions={
        <>
          <div style={{ width: 170 }}>
            <SearchableSelect value={source} onChange={setSource}
              options={[{ value: '', label: 'All sources' }, ...sourceOptions.map(s => ({ value: s, label: s }))]}
              placeholder="All sources" />
          </div>
          <Segmented options={RANGES} value={days} onChange={setDays} />
        </>
      }
    >
      {/* KPI row */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 18, flexWrap: 'wrap' }}>
        {loading ? [0, 1, 2, 3].map(i => <div key={i} style={{ flex: 1 }}><Shimmer height={92} radius={12} /></div>) : (
          <>
            <KpiCard label="New Leads" icon={Users} value={k.newLeads} info={`Leads created in the last ${days} days.`} />
            <KpiCard label="Cost / Lead" icon={IndianRupee} value={fmtINR(k.costPerLead)} info="Active campaign spend ÷ leads generated by active campaigns." />
            <KpiCard label="Active Spend" icon={Megaphone} value={fmtINR(k.activeSpend)} info="Total spend across campaigns currently marked active." />
            <KpiCard label="Enrollments" icon={GraduationCap} value={k.enrollments} accent={C.green} info={`Leads that reached Enrolled in the last ${days} days.`} />
          </>
        )}
      </div>

      {/* Ad-loop activity: the two halves of the click → conversation → conversion
          chain, each a summary with a way through to the full tab. */}
      {canSeeCtwa && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(380px, 1fr))', gap: 16, marginBottom: 16 }}>
          <CtwaStrip data={ctwa} days={days} navigate={navigate} />
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: 16, marginBottom: 16 }}>
        <Card title="Leads by source">
          {loading ? <Shimmer height={180} /> :
            <Donut data={(data?.bySource || []).map((s, i) => ({ label: s.source, value: s.count, color: SERIES[i % SERIES.length] }))} />}
        </Card>
        <Card title="Funnel snapshot" right={<LinkText onClick={() => navigate && navigate('leads')}>Open pipeline</LinkText>}>
          {loading ? <Shimmer height={180} /> :
            <FunnelBars data={(data?.funnel || []).map(f => ({ stage: f.stage, count: f.count }))}
              colorFor={(f) => STAGE_META[f.stage]?.color} onClick={() => navigate && navigate('leads')} />}
        </Card>
      </div>

      <Card title="Leads trend" style={{ marginBottom: 16 }}>
        {loading ? <Shimmer height={150} /> : <LineTrend data={data?.trend || []} />}
      </Card>

      {/* ── Lead sources (was its own tab) ─────────────────────────────────── */}
      <Card title="Lead sources"
        right={<span style={{ fontSize: 14, color: C.textMuted, fontFamily: FONT }}>Ranked by quality, not just volume</span>}>
        {!sources ? <Shimmer height={220} radius={10} /> : (
          <Table
            columns={[{ label: 'Source' }, { label: 'Leads', align: 'right' }, { label: 'Entry Stage' },
              { label: '→ Hot' }, { label: '→ Enrolled' },
              { label: 'Cost / Lead', align: 'right' }]}
            rows={sources} keyOf={s => s.source}
            empty={<EmptyState Icon={GitBranch} title="No lead sources yet"
              hint="Sources are set automatically from where each conversation started." />}
            onRowClick={() => navigate && navigate('leads', 'list')}
            renderRow={(s) => (
              <>
                <Td bold>{s.source}</Td>
                <Td align="right" mono>{s.leads}</Td>
                <Td color={C.textSecondary} style={{ textTransform: 'capitalize' }}>{s.entryStage}</Td>
                <Td><Bar pct={s.hotPct} color={C.amber} /></Td>
                <Td><Bar pct={s.enrolledPct} color={C.green} /></Td>
                <Td align="right" mono>{s.costPerLead != null ? fmtINR(s.costPerLead) : '—'}</Td>
              </>
            )}
          />
        )}
      </Card>
    </PageShell>
  );
}

function Bar({ pct, color }) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 7 }}>
      <span style={{ width: 54, height: 6, borderRadius: 4, background: C.hover, overflow: 'hidden' }}>
        <span style={{ display: 'block', width: `${Math.min(100, pct)}%`, height: '100%', background: color }} />
      </span>
      <span style={{ fontFamily: MONO, fontSize: 14, color: C.text, minWidth: 32 }}>{pct}%</span>
    </span>
  );
}

function LinkText({ onClick, children }) {
  return (
    <span onClick={onClick}
      style={{ fontSize: 14, color: C.primary, cursor: 'pointer', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 4 }}>
      {children} <ArrowRight size={12} />
    </span>
  );
}

function Stat({ label, value, accent }) {
  return (
    <div style={{ minWidth: 74 }}>
      <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.06em', textTransform: 'uppercase', color: C.textMuted }}>{label}</div>
      <div style={{ fontSize: 18, fontWeight: 700, fontFamily: MONO, color: accent || C.text, marginTop: 2 }}>{value}</div>
    </div>
  );
}

// ── Click-to-WhatsApp strip ─────────────────────────────────────────────────
function CtwaStrip({ data, days, navigate }) {
  return (
    <Card title="Click-to-WhatsApp"
      right={<LinkText onClick={() => navigate && navigate('ctwa-ads')}>Open</LinkText>}>
      {data === null ? <Shimmer height={110} /> : data === false ? (
        <div style={{ fontSize: 14, color: C.textMuted, fontFamily: FONT }}>Not available for your account.</div>
      ) : (
        <>
          <div style={{ display: 'flex', alignItems: 'center', gap: 9, marginBottom: 12 }}>
            <MousePointerClick size={15} color={C.textSecondary} />
            <span style={{ fontSize: 14, color: C.textSecondary, fontFamily: FONT }}>
              Conversations that started from an ad, last {days} days.
            </span>
          </div>
          <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap', marginBottom: 12 }}>
            <Stat label="Clicks" value={num(data.kpis?.clicks)} />
            <Stat label="Leads" value={num(data.kpis?.leads)} />
            <Stat label="Enrolled" value={num(data.kpis?.enrolled)} accent={C.green} />
            <Stat label="Cost/Lead" value={data.kpis?.costPerLead != null ? fmtINR(data.kpis.costPerLead) : '—'} />
            <Stat label="ROAS" value={data.kpis?.roas != null ? `${data.kpis.roas.toFixed(2)}x` : '—'}
              accent={data.kpis?.roas >= 1 ? C.green : C.text} />
          </div>
          {(data.allPlatforms || []).length > 0 && (
            <div style={{ display: 'flex', gap: 7, flexWrap: 'wrap', borderTop: `1px solid ${C.border}`, paddingTop: 10 }}>
              {(data.allPlatforms || []).slice(0, 4).map(p => (
                <Badge key={p.platform} label={`${p.platform} · ${num(p.clicks)}`} color={C.textSecondary} bg={C.hover} />
              ))}
            </div>
          )}
        </>
      )}
    </Card>
  );
}

